#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "VitiWork cutover — OAuth and extra-repo retirement"

# ── 1. Confirm copies on main ────────────────────────────────────────────
stage "Confirm copies on main"
say "Do not archive anything until docs/ and the Next homepage (VitiWork copy) are on branch main of F1J197/F1J1-Jobs."
open_url "https://github.com/F1J197/F1J1-Jobs"
if ! confirm "Are docs/ and the VitiWork homepage on main?"; then
  warn "Do not archive extra repos until those copies are on main."
fi

# ── 2. Facebook OAuth ────────────────────────────────────────────────────
stage "Facebook OAuth"
say "Create a Facebook app, add Facebook Login, then copy the App ID and App Secret."
open_url "https://developers.facebook.com/apps/"
step "Create an app (or open an existing one) for VitiWork."
step "Add the Facebook Login product."
step "Set the Valid OAuth Redirect URI to {NEXTAUTH_URL}/api/auth/callback/facebook (local: http://localhost:3000/api/auth/callback/facebook)."
step "On Settings → Basic, copy the App ID and App Secret."
ask FACEBOOK_CLIENT_ID "Paste the Facebook App ID:"
ask_secret FACEBOOK_CLIENT_SECRET "Paste the Facebook App Secret:"
write_env FACEBOOK_CLIENT_ID "$FACEBOOK_CLIENT_ID"
write_env FACEBOOK_CLIENT_SECRET "$FACEBOOK_CLIENT_SECRET"

# ── 3. Google OAuth ──────────────────────────────────────────────────────
stage "Google OAuth"
say "Create a Google OAuth client (Web) and capture NextAuth settings."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create an OAuth client ID of type Web application."
step "Set the authorized redirect URI to {NEXTAUTH_URL}/api/auth/callback/google (local: http://localhost:3000/api/auth/callback/google)."
step "Copy the Client ID and Client secret."
ask GOOGLE_CLIENT_ID "Paste the Google Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Google Client secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
note "NEXTAUTH_SECRET can be any long random string (e.g. openssl rand -base64 32)."
ask_secret NEXTAUTH_SECRET "Paste NEXTAUTH_SECRET:"
ask NEXTAUTH_URL "NEXTAUTH_URL (default http://localhost:3000):"
[[ -z "$NEXTAUTH_URL" ]] && NEXTAUTH_URL="http://localhost:3000"
write_env NEXTAUTH_SECRET "$NEXTAUTH_SECRET"
write_env NEXTAUTH_URL "$NEXTAUTH_URL"

# ── 4. Confirm DATABASE_URL ──────────────────────────────────────────────
stage "Confirm DATABASE_URL"
say "Prisma needs DATABASE_URL in .env."
if [[ -f docker-compose.yml ]]; then
  note "docker-compose.yml is in this repo — local Postgres is postgresql://fijijobs:fijijobs_dev_password@localhost:5432/fiji_jobs"
fi
ask DATABASE_URL "Paste DATABASE_URL:"
write_env DATABASE_URL "$DATABASE_URL"

# ── 5. Archive fiji-jobs ─────────────────────────────────────────────────
stage "Archive fiji-jobs"
warn "Archiving is irreversible."
say "Only archive F1J197/fiji-jobs. Do not archive any other repository."
open_url "https://github.com/F1J197/fiji-jobs/settings"
if confirm "Type yes only if copies are on main and you will archive fiji-jobs"; then
  step "Settings → Danger zone → Archive this repository."
  pause "Press Enter after you have archived fiji-jobs (or stopped)."
else
  say "Skipped. fiji-jobs was not archived."
fi

# ── 6. Archive vitiwork-landing ──────────────────────────────────────────
stage "Archive vitiwork-landing"
warn "Archiving is irreversible."
say "Only archive F1J197/vitiwork-landing after the landing copy is in this repo's homepage."
open_url "https://github.com/F1J197/vitiwork-landing/settings"
if confirm "Type yes only if the landing copy is on the homepage and you will archive vitiwork-landing"; then
  step "Settings → Danger zone → Archive this repository."
  pause "Press Enter after you have archived vitiwork-landing (or stopped)."
else
  say "Skipped. vitiwork-landing was not archived."
fi

# ── 7. Optional rename ───────────────────────────────────────────────────
stage "Optional rename"
say "You may rename F1J197/F1J1-Jobs to vitiwork. This is optional."
note "Renaming the GitHub repo does not change git history."
open_url "https://github.com/F1J197/F1J1-Jobs/settings"
if confirm "Rename F1J1-Jobs to vitiwork now?"; then
  step "Settings → General → Repository name → rename to vitiwork, then confirm."
  pause "Press Enter after you have renamed (or decided not to)."
else
  say "Skipped. You can rename later."
fi

finish
